apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-test
  template:
    metadata:
      labels:
        app: cloud-test
    spec:
      containers:
      - name: custom-app
        # CRITICAL: Kubernetes pulls your exact public image from Docker Hub here
        image: galgalcloudeg/cloud-test-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-test-service
spec:
  selector:
    app: cloud-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
